Add Game Developments Courses / Badges🏅
PanXProject/awesome-certificates pull request #51
Opened 2024-06-16 07:13 UTC by PrathamArtz

##  Added 5 Unity pathway / Courses, with proper Game Development Section.

### 1. Unity Essentials
### 2. Junior Programmer
### 3. Creative Core
### 4. VR Development
### 5.  Mobile AR Development

2024-06-16 07:14 UTC, PrathamArtz commented
unicorn

2024-06-23 20:44 UTC, waleedsadek-panx commented on .vs/Open_source/v17/.wsuo
Delete this file

2024-06-23 20:45 UTC, waleedsadek-panx commented on .vs/Open_source/v17/DocumentLayout.json
Delete this file

2024-06-23 20:45 UTC, waleedsadek-panx commented on .vs/slnx.sqlite
Delete this file

2024-06-23 20:56 UTC, waleedsadek-panx commented on README.md
- [ ] On line 62 change `- [Game Devlopement](#Game-developement)` to `- [Game Development](#game-development)`  
- [ ] Delete line 90 and 365
- [ ] On line 374 change `## Game-developement` to `## Game Development`
- [ ] Delete line 375 and 376

2024-06-23 21:02 UTC, waleedsadek-panx requested changes
Thanks for your contribution! 🚀 Kindly make these amends, so I can merge your request! Let me know if you need anything.

- [ ]  On line 62 change `- [Game Devlopement](#Game-developement)` to `- [Game Development](#game-development)` and add it before `[Other Awesome Lists](#other-awesome-lists)`
- [ ] Delete line 90 and 365
- [ ] On line 374 change `## Game-developement` to `## Game Development`
- [ ] Delete line 375 and 376
- [ ] Delete file `.vs/Open_source/v17/.wsuo`
- [ ] Delete file `.vs/Open_source/v17/DocumentLayout.json`
- [ ] Delete file `.vs/VSWorkspaceState.json`
- [ ] Delete file `.vs/slnx.sqlite`

2024-06-23 21:03 UTC, waleedsadek-panx commented
Thanks for hunting down these new certificates! I left a couple of notes before I can merge.

2024-06-23 21:14 UTC, waleedsadek-panx commented on README.md
> -
Add space so it's two lines after every table.

2024-06-24 18:03 UTC, closed without merging